sudo: required
language: generic
services:
  - docker

before_install: 
  - docker build -t dhdepna/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true dhdepna/react-test npm run test

after_success:
# Build production images
  - docker build -t dhdepna/multi-client ./client
  - docker build -t dhdepna/multi-nginx ./nginx
  - docker build -t dhdepna/multi-server ./server
  - docker build -t dhdepna/multi-worker ./worker
# Log in to docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
# Take the images above and push them to DockerHub
  - docker push dhdepna/multi-client
  - docker push dhdepna/multi-nginx
  - docker push dhdepna/multi-server
  - docker push dhdepna/multi-worker
